In [2]:
import tensorflow as tf

In [3]:
#update version
tf.config.run_functions_eagerly(True)  #enable eager execution (if not already enabled)
a=tf.constant("hello world")   #a is variable creating
print(a)

tf.Tensor(b'hello world', shape=(), dtype=string)


In [4]:
print(a.numpy())

b'hello world'


In [5]:
#old version is
a=a=tf.constant("hello world")
print(a)

b=tf.Session()
print(b.run(a))
b.close()

tf.Tensor(b'hello world', shape=(), dtype=string)


AttributeError: module 'tensorflow' has no attribute 'Session'

In [7]:
#scalar
a=tf.constant(10)
b=tf.constant(3.14)
c=tf.constant("hello")
print(a,'\n',b,'\n',c)
print(a.numpy(),'\n',b.numpy(),'\n',c.numpy(),'\n')

#vector
a=tf.constant([1,2,3,4])
b=tf.constant([5.0,6.2,7.5,8.8])
print(a,'\n',b,'\n')
print(a.numpy(),'\n',b.numpy(),'\n')

#matrix
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[5.0],[6.2]])
print(a,'\n',b,'\n')
print(a.numpy(),'\n',b.numpy(),'\n')

#higher-dimensional Tensor constant
a=tf.constant([[[1,2,0],[3,4,0]],[[5,6,0],[7,8,0]]])
print(a)
print(a.numpy())

#boolean
a=tf.constant(True)
print(a)
print(a.numpy())

#special constant

a=tf.zeros(shape=(3,3))
b=tf.ones(shape=(3,3))
print(a,'\n',b)
print(a.numpy(),'\n',b.numpy())




tf.Tensor(10, shape=(), dtype=int32) 
 tf.Tensor(3.14, shape=(), dtype=float32) 
 tf.Tensor(b'hello', shape=(), dtype=string)
10 
 3.14 
 b'hello' 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 
 tf.Tensor([5.  6.2 7.5 8.8], shape=(4,), dtype=float32) 

[1 2 3 4] 
 [5.  6.2 7.5 8.8] 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 
 tf.Tensor(
[[5. ]
 [6.2]], shape=(2, 1), dtype=float32) 

[[1 2]
 [3 4]] 
 [[5. ]
 [6.2]] 

tf.Tensor(
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]], shape=(2, 2, 3), dtype=int32)
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]
tf.Tensor(True, shape=(), dtype=bool)
True
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) 
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#multiplication 
a=tf.constant(5.0)
b=tf.constant(3.0)
c=a*b
d=tf.multiply(a,b)
print(c)
print(c.numpy())
print(d)
print(d.numpy())

tf.Tensor(15.0, shape=(), dtype=float32)
15.0
tf.Tensor(15.0, shape=(), dtype=float32)
15.0


In [12]:
#multiplication of matrix
tf.config.run_functions_eagerly(True)
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[1,2],[3,4]])
c=a*b
d=tf.multiply(a,b)
print(c)
print(c.numpy())
print(d)
print(d.numpy())

c=a@b
print(c)
print(c.numpy())

c=tf.matmul(a,b)
print(c)
print(c.numpy())


tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
[[ 1  4]
 [ 9 16]]
tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)
[[ 1  4]
 [ 9 16]]
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
[[ 7 10]
 [15 22]]
tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
[[ 7 10]
 [15 22]]


In [14]:
a=tf.constant(1.25)
print(a)
b=tf.cast(a,dtype=tf.int32)
print(b,'\n',b.numpy())

tf.Tensor(1.25, shape=(), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32) 
 1


In [15]:
x=tf.constant([[1,2],[3,4]])
e=tf.transpose(x)
print(e.numpy())
d=tf.reduce_sum(x)
print(d.numpy())

[[1 3]
 [2 4]]
10


In [19]:
x=tf.constant([[1.,2.,5.],[3.,4.,8.]])
d=tf.concat([x,x,x],axis=1)
print(d.numpy())
d=tf.concat([x,x,x],axis=0)
print(d.numpy())

[[1. 2. 5. 1. 2. 5. 1. 2. 5.]
 [3. 4. 8. 3. 4. 8. 3. 4. 8.]]
[[1. 2. 5.]
 [3. 4. 8.]
 [1. 2. 5.]
 [3. 4. 8.]
 [1. 2. 5.]
 [3. 4. 8.]]


In [37]:
logits=tf.constant([20.0,30.0,40.0,50.0,60.0])
x=tf.constant([[1.,2.,5.],[3.,4.,8.]])
softmax_probs=tf.nn.softmax(logits,axis=0)
print(softmax_probs)
softmax_probs=tf.nn.softmax(x,axis=0)
print(softmax_probs)

tf.Tensor([4.2481614e-18 9.3571980e-14 2.0610598e-09 4.5397872e-05 9.9995458e-01], shape=(5,), dtype=float32)
tf.Tensor(
[[0.11920291 0.11920291 0.04742587]
 [0.880797   0.880797   0.95257413]], shape=(2, 3), dtype=float32)


In [47]:
import pandas as pd

input_file = 'inpu.txt'
    # Read the text file into a pandas DataFrame
df = pd.read_csv(input_file, delimiter='\t', header=None)  # Assuming tab-separated text file without header
print(df)
    # Write the DataFrame to a CSV file
df.to_csv('output.csv', index=False)  # Set index=False to exclude row numbers in output

# Usage example
df1= pd.read_csv('output.csv')
print(df1)




                                                      0
0     9/26/23, 08:56 - Messages and calls are end-to...
1     9/26/23, 11:25 - Messages and calls are end-to...
2     9/30/23, 11:41 - Disappearing messages were tu...
3     9/30/23, 11:41 - Venkatesh(Cse-a): https://git...
4        9/30/23, 18:52 - Tarun: Cheyledu chesta annadu
...                                                 ...
1206  except (ConnectionError, Timeout, TooManyRedir...
1207                                           print(e)
1208  2/20/24, 11:10 - Tarun: dba4504e-635c-4ef4-974...
1209  2/20/24, 12:12 - Tarun: 8efed61fa2bf667d037d80...
1210  2/20/24, 12:14 - Tarun: http://api.openweather...

[1211 rows x 1 columns]
                                                      0
0     9/26/23, 08:56 - Messages and calls are end-to...
1     9/26/23, 11:25 - Messages and calls are end-to...
2     9/30/23, 11:41 - Disappearing messages were tu...
3     9/30/23, 11:41 - Venkatesh(Cse-a): https://git...
4        9/30/23, 18:52

In [49]:
pip install fpdf

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40712 sha256=7f457f03b8daf8fe1fcc4a39d8306c7d8a75dd2f4d53125fdbbe62126b6bfc7e
  Stored in directory: c:\users\b.venkateswara rao\appdata\local\pip\cache\wheels\f9\95\ba\f418094659025eb9611f17cbcaf2334236bf39a0c3453ea455
Successfully built fpdf
Note: you may need to restart the kernel to use updated packages.


In [55]:
import pandas as pd
from fpdf import FPDF

# Read the CSV file
data = pd.read_csv('output.csv')

# Convert DataFrame to a string
data_str = data.to_string(index=False)

# Initialize the PDF
pdf = FPDF()
pdf.add_page()
pdf.set_font("Arial", size=12)

# Add the DataFrame content to the PDF
# Encode the string using UTF-8 to avoid UnicodeEncodeError
pdf.multi_cell(0, 10, data_str.encode('utf-8').decode('latin-1'))

# Save the PDF file
pdf.output("WhatsApp_Chat.pdf")

print("PDF successfully created!")

PDF successfully created!
